name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest

    steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 6.0.2

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test
